// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package note

import (
	"context"
	"github.com/donnol/jdnote/models/note"
)

// Injectors from inject.go:

func InitNote(ctx context.Context) (note.Noter, error) {
	noter := note.New()
	return noter, nil
}
