# This is a TOML document.

title = "jdnote project"

[owner]
name = "jdlau"

[server]
port = ":8810"

[database]
scheme = "postgres"
host = "127.0.0.1"
port = 5432
user = "jd"
password = "jd"
name = "cicada"

[jwt]
secret = "Xadfdfoere23242l2afasf34wraf090uadfrfdIEJF039039"